version: '3.2'
services:
  # https://hub.docker.com/_/postgres/
  postgre-db:
    image: postgres:10.5
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - pick-em-network
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - pick-em-network
    ports:
      - 8080:8080     

networks:
  pick-em-network:
    driver: bridge